config/routes.rb
Rails.application.routes.draw do
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @pages = Page.all
    end

    def new
        @page = Page.new
    end

    def create
        @page = Page.new(page_params)

        if @page.save
            redirect_to pages_path
        else
            render :new
        end
    end

    def show
        @page = Page.find(params[:id])
    end

    def destroy
        @page = Page.find(params[:id])
        @page.destroy

        redirect_to pages_path
    end


    private

    def page_params
        params.require(:page).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

    def markdown(text)
        Markdown.new(text, extensions = {}).to_html.html_safe
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArticleMd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Articles</h1>

<%= link_to 'new', new_page_path %>

<table>
    <% @pages.each do |page| %>
        <h2><%= link_to page.title, page %></h2> 
    <% end %>
</table>

app/views/pages/new.html.erb
<h1>Add new article</h1>

<%= form_for(@page) do |f| %>
    <%= f.label :title, 'title'%><br>
    <%= f.text_field :title%>

    <%= f.label :body, style: "display: block"%><br>
    <%= f.text_area :body, rows: 30, style: 'width: 50%'%><br>

    <%= f.submit %>
<% end %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<div>
    <h1><%= @page.title%></h1>
    <p>
        <%= markdown @page.body %>  
    </p>
</div>


<%= button_to 'Delete', page_path(@page), method: :delete, data: {confirm: 'Are you sure?'} %>